Show/Hide API Password
opencast-ilias/OpenCast pull request #210
Opened 2023-10-25 10:23 UTC by ferishili

This PR fixes #206,

### Description
refer to the issue

### How it works
- The API password now gets the dot mask when the page is loaded
- The ability to show/hide the password is also provided, via the eye icon on the right side of the password input.

### Important to note:
- 2 svg files have been added into /templates/images
- 1 js file and 1 css file responsible to do the job are also added

2023-10-25 12:19 UTC, reiferschris approved these changes
Works as advertised :D Thank you. 
Finally, no more spoiling the api password when showing someone the plugin settings.

2023-10-26 06:45 UTC, chfsx requested changes
Hi! thanks for this suggestion, I ahbe some change requests written as comments.

but basically the following question arises: there is a lot of new code for this functionality. as soon as we rebuild the forms (from legacy-forms to UI-components) we will have to rework all this again. but if you want to do this at the moment, i can't decide, maybe @Amstutz could give an opinion.

otherwise the PR would be ok after the changes, best thanks for the work!

2023-10-26 06:45 UTC, chfsx commented on classes/Conf/class.xoctConfFormGUI.php
> +        global $DIC;
@ferishili could you move this (as $this->main_template = ...) to the constructor?

2023-10-26 06:45 UTC, chfsx commented on classes/Conf/class.xoctConfFormGUI.php
> +        $main_tpl->addJavaScript($this->plugin->getStyleSheetLocation('default/password_toggle.min.js'));
this should be changes to ->addOnloadCode() and you should pass something like an `init('#elemt_id')` method. please have a look to my comment in password_toggle.js

2023-10-26 06:45 UTC, chfsx commented on templates/default/password_toggle.js
> +$(document).ready(function() {
Please rewrite this according to https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/js-bundling.md

this results in a small module which then can be used with an init-method (see comment above) like PasswordToggle.init().

I think that we should increasingly centralize JS in the plugin and gradually bring it into this form. we can therefore start directly with this JS

2023-10-26 06:45 UTC, chfsx commented on templates/default/password_toggle.js
> +	let password_input = document.getElementById('curl_password');
the modification also means that we no longer have a direct bundling to exactly this element but the functionality could also be used for other password inputs.

2023-10-27 06:19 UTC, chfsx commented
HI @ferishili I opened a PR with the changes to move the JS code to the new structure: https://github.com/elan-ev/ilias-opencast-plugin/pull/3

2023-10-27 07:01 UTC, ferishili commented
Hi @chfsx, thanks a lot.

2023-10-27 08:27 UTC, chfsx approved these changes
Thanks a lot for the changes!

2023-10-27 08:53 UTC, Amstutz commented
Thx a lot!

2023-10-27 08:53 UTC, merged