[FIX] db-update issues when switching to new release_* branches
opencast-ilias/OpenCast pull request #257
Opened 2024-03-07 15:15 UTC by chfsx

This PR solves several issues concerning the database when switching from old versions (prior to 5.6) to release_7 (the same PR will be introduced for release_8 as well). See #251 https://github.com/opencast-ilias/OpenCast/issues/252#issuecomment-1975867210

@ferishili thanks for your help and @reiferschris for the finding as well!

2024-03-07 15:16 UTC, chfsx commented on sql/dbupdate.php
> +// Dear colleague!
@ferishili I introduced this comment here to remind ourself and other to discuss the introduction of new steps :-)

2024-03-07 15:24 UTC, ferishili commented on sql/dbupdate.php
> +// Dear colleague!
Well explained, thank you very much.

2024-03-07 15:29 UTC, ferishili requested changes

2024-03-07 15:29 UTC, ferishili commented on sql/dbupdate.php
> +if($ilDB->tableColumnExists('xoct_workflow', 'parameter')) {
The field is called `parameters` and the fix has `parameter`
This also applies to the latest step!

2024-03-07 15:29 UTC, ferishili requested changes

2024-03-07 15:29 UTC, ferishili commented on sql/dbupdate.php
> +if($ilDB->tableColumnExists('xoct_workflow', 'parameter')) {
Here as well: `parameters`

2024-03-07 15:33 UTC, ferishili approved these changes

2024-03-07 15:33 UTC, ferishili commented
Well done, thanks a lot

2024-03-25 13:47 UTC, dagraf commented
I close this PR, since it got included in #258 and #255.

2024-03-25 13:47 UTC, closed without merging