[FIX] introduce "title" as mandatory MD for series
opencast-ilias/OpenCast pull request #364
Opened 2024-10-29 19:10 UTC by chfsx

This PR should fix the issue in #328 

Currently it's possible to delete or never configure the metadata field "title" for series. This leads to errors on both sides, ILIAS and even opencast.

The fix introduces an update step which creates the missing field if it doesn't exist. beside that, the MD definition now holds a "mandatory" flag und the delete action is no longer available for mandatory fields.

2024-11-06 13:53 UTC, dagraf commented
Thx for the PR. I appreciate the fix and can confirm the changes.

Therefore and @Amstutz: Can you please review this PR and merge it if everything is fine or comment it, if not? Thx!

2024-11-06 13:59 UTC, Amstutz commented
Hey @chfsx 

Thx a lot for the changes. I can only superficially check the changes, however to me they look good. Maybe @ferishili can have an other glance. 

Special thx for improving the overall code quality with the PR with some minor neat little refactorings (such as types).

2024-11-07 14:02 UTC, ferishili requested changes

2024-11-07 14:02 UTC, ferishili commented on classes/Conf/Metadata/class.xoctMetadataConfigGUI.php
> +     * @param array $raw_list  the raw list that comes from the listprovider endpoints
Would be nice to remove extra space!

```suggestion
     * @param array $raw_list the raw list that comes from the listprovider endpoints
```

2024-11-07 14:02 UTC, ferishili commented on classes/Setup/class.ilOpenCastDBUpdateSteps.php
> +                'title_en' => ['text', 'Ttitle'],
"Ttitle" or Title?
```suggestion
                'title_en' => ['text', 'Title'],
```

2024-11-07 14:02 UTC, ferishili commented on src/Model/Metadata/Definition/MDCatalogueFactory.php
> +            new MDFieldDefinition(MDFieldDefinition::F_TITLE, MDDataType::text(), false, true, true), // Title is Mandatory for Series
I like the Mandatory option here.
That would be good to have that also for Event in terms of consistency in
 https://github.com/opencast-ilias/OpenCast/blob/a0392d8852b42c777aed9eb6eba966c2fd38cb5c/src/Model/Metadata/Definition/MDCatalogueFactory.php#L19

2024-11-07 14:05 UTC, ferishili commented
Hi @chfsx,
Thanks for your work and also the improvements. Everything works fine.
I added a few minor changes.

2024-11-07 14:07 UTC, chfsx commented on src/Model/Metadata/Definition/MDCatalogueFactory.php
> +            new MDFieldDefinition(MDFieldDefinition::F_TITLE, MDDataType::text(), false, true, true), // Title is Mandatory for Series
Thanks, I was thinking about that as well. But I'm not sure if its really mandatory for events as well (on the Opencast-side), does anybody know?

2024-11-07 14:08 UTC, chfsx commented
Thanks for the findings and suggestions! I merged them where possible, concerning the mandatory title in event: I just lack of opencast knowledge there...

2024-11-07 14:15 UTC, ferishili commented on src/Model/Metadata/Definition/MDCatalogueFactory.php
> +            new MDFieldDefinition(MDFieldDefinition::F_TITLE, MDDataType::text(), false, true, true), // Title is Mandatory for Series
Of course, it is mandatory for events too, however, the External API will return an error if you forget it, unlike Series!

2024-11-12 18:37 UTC, ferishili commented on src/Model/Metadata/Definition/MDCatalogueFactory.php
> +            new MDFieldDefinition(MDFieldDefinition::F_TITLE, MDDataType::text(), false, true, true), // Title is Mandatory for Series
Ping!

2024-11-12 18:45 UTC, chfsx commented
@ferishili thanks for the feedback concerning events, I added another commit to make this mandatory as well

2024-11-13 13:18 UTC, ferishili commented
> @ferishili thanks for the feedback concerning events, I added another commit to make this mandatory as well

Hi @chfsx,
I cannot see your commit/any changes regarding this!

2024-11-14 12:15 UTC, ferishili reviewed
Thanks for the changes, it looks good to me. As soon as the suggestion is applied, this could be merged.

2024-11-14 12:15 UTC, ferishili commented on classes/Setup/class.ilOpenCastDBUpdateSteps.php
> +        // check for missing mandatory "title" MD for series
This step would not be necessary, but as for a double-checker I would say, that is ok.
A small typo:
```suggestion
        // check for missing mandatory "title" MD for event
```

2024-11-18 14:19 UTC, ferishili commented on classes/Setup/class.ilOpenCastDBUpdateSteps.php
> +        // check for missing mandatory "title" MD for series
@chfsx Ping! 
The small suggestion could be applied, and then we could get it merged!

2024-11-19 19:17 UTC, chfsx commented
Thanks a lot, I will rebase, merge and squash locally and release e new version which includes other fixes as well

2024-11-19 20:55 UTC, ferishili approved these changes

2024-11-28 09:14 UTC, chfsx commented
This has been merged locally and is part of v8.2.8

2024-11-28 09:14 UTC, closed without merging